# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

x-logging:
  &default-logging
  driver: "splunk"
  options:
    splunk-token: "12345678-ABCD-EFGH-IJKL-123456789012"
    splunk-url: "https://localhost:18088"
    splunk-insecureskipverify: "true"
    splunk-verify-connection: "false"
    splunk-format: "json"
    tag: "{{.Name}}-{{.ID}}"
    env: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
x-environment:
  &default-environment
  FABRIC_LOGGING_FORMAT: json
  CORE_METRICS_PROVIDER: statsd
  CORE_METRICS_STATSD_NETWORK: udp
  CORE_METRICS_STATSD_ADDRESS: splunk.example.com:8125
  ORDERER_METRICS_PROVIDER: statsd
  ORDERER_METRICS_STATSD_NETWORK: udp
  ORDERER_METRICS_STATSD_ADDRESS: splunk.example.com:8125

networks:
  byfn:

services:
  splunk.example.com:
    container_name: splunk.example.com
    image: splunk/splunk:7.2.3
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_APPS_URL=http://s3.amazonaws.com/splunk-hyperledger/status-indicator-custom-visualization_130.tgz,http://s3.amazonaws.com/splunk-hyperledger/splunk-metrics-workspace_101.tgz,http://s3.amazonaws.com/splunk-hyperledger/fabric/${BRANCH}/splunk-hyperledger-fabric.tgz
    networks:
      - byfn
    ports:
      - "18000:8000"
      - "18088:8088"

  cadivsor.example.com:
    container_name: cadvisor.example.com
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --storage_driver=statsd
      - --storage_driver_host=splunk.example.com:8125
      - --docker_only=true
    networks:
      - byfn
    user: root

  febric-logger.example.com:
    container_name: fabric-logger.example.com
    image: splunkdlt/fabric-logger:latest
    environment:
      - FABRIC_KEYFILE=${BUTTERCUP_ADMIN_PK}
      - FABRIC_CERTFILE=crypto/peerOrganizations/buttercup.example.com/users/Admin@buttercup.example.com/msp/signcerts/Admin@buttercup.example.com-cert.pem
      - FABRIC_MSP=ButtercupMSP
      - FABRIC_PEER=peer0.buttercup.example.com
      - SPLUNK_HEC_TOKEN=12345678-ABCD-EFGH-IJKL-123456789012
      - SPLUNK_HOST=splunk.example.com
      - SPLUNK_PORT=8088
      - SPLUNK_INDEX=hyperledger_logs
      - LOGGING_LOCATION=splunk
      - NETWORK_CONFIG=network.yaml
    volumes:
      - ./crypto:/usr/src/app/crypto/
      - ./network.yaml:/usr/src/app/network.yaml
    depends_on:
      - orderer.example.com
      - peer0.buttercup.example.com
      - peer1.buttercup.example.com
      - peer0.popstar.example.com
      - peer1.popstar.example.com
    networks:
      - byfn

  orderer.example.com:
    environment: 
      <<: *default-environment
      ORDERER_METRICS_STATSD_PREFIX: orderer.example.com
    logging: *default-logging
    depends_on:
      - splunk.example.com

  peer0.buttercup.example.com:
    environment: 
      <<: *default-environment
      CORE_METRICS_STATSD_PREFIX: peer0.buttercup.example.com
    logging: *default-logging
    depends_on:
      - splunk.example.com

  peer1.buttercup.example.com:
    environment: 
      <<: *default-environment
      CORE_METRICS_STATSD_PREFIX: peer1.buttercup.example.com
    logging: *default-logging
    depends_on:
      - splunk.example.com

  peer0.popstar.example.com:
    environment : 
      <<: *default-environment  
      CORE_METRICS_STATSD_PREFIX: peer0.popstar.example.com
    logging: *default-logging
    depends_on:
      - splunk.example.com

  peer1.popstar.example.com:
    environment: 
      <<: *default-environment  
      CORE_METRICS_STATSD_PREFIX: peer1.popstar.example.com
    logging: *default-logging
    depends_on:
      - splunk.example.com

  cli:
    environment: 
      <<: *default-environment
      CORE_METRICS_STATSD_PREFIX: cli
    logging: *default-logging
    depends_on:
      - splunk.example.com
