set -ex

export FABRIC_CFG_PATH=${PWD}/scripts/config
export IMAGE_TAG="latest"
export CONSENSUS_TYPE="kafka"
export COMPOSE_PROJECT_NAME="buttercup-games"

# Using docker-compose-e2e-template.yaml, replace constants with private key file names
# generated by the cryptogen tool and output a docker-compose.yaml specific to this
# configuration
function replacePrivateKey() {
  # sed on MacOSX does not support -i flag with a null extension. We will use
  # 't' for our back-up's extension and delete it at the end of the function
  ARCH=$(uname -s | grep Darwin)
  if [ "$ARCH" == "Darwin" ]; then
    OPTS="-it"
  else
    OPTS="-i"
  fi

  # Copy the template to the file that will be modified to add the private key
  cp docker-compose-e2e-template.yaml docker-compose-e2e.yaml

  # The next steps will replace the template's contents with the
  # actual values of the private key file names for the two CAs.
  CURRENT_DIR=$PWD
  cd crypto/peerOrganizations/pony.example.com/ca/
  PRIV_KEY=$(ls *_sk)
  cd "$CURRENT_DIR"
  sed $OPTS "s/CA1_PRIVATE_KEY/${PRIV_KEY}/g" docker-compose-e2e.yaml
  cd crypto-config/peerOrganizations/toby.example.com/ca/
  PRIV_KEY=$(ls *_sk)
  cd "$CURRENT_DIR"
  sed $OPTS "s/CA2_PRIVATE_KEY/${PRIV_KEY}/g" docker-compose-e2e.yaml
  # If MacOSX, remove the temporary backup of the docker-compose file
  if [ "$ARCH" == "Darwin" ]; then
    rm docker-compose-e2e.yamlt
  fi
}


if [ -d "crypto" ]; then
	rm -Rf crypto
fi
cryptogen generate --config=./scripts/config/crypto-config.yaml --output "crypto"

configtxgen -profile SampleDevModeKafka -channelID byfn-sys-channel -outputBlock ./channel-artifacts/genesis.block

docker-compose -f docker-compose-cli.yaml \
			   -f docker-compose-kafka.yaml \
			   -f docker-compose-couch.yaml \
			   -f docker-compose-splunk.yaml \
			   -f docker-compose-splunk-couch.yaml \
			   -f docker-compose-splunk-kafka.yaml up -d